2022-02-23 17:15:35,535 INFO    MainThread:32031 [wandb_setup.py:_flush():71] setting env: {}
2022-02-23 17:15:35,535 INFO    MainThread:32031 [wandb_setup.py:_flush():71] setting login settings: {}
2022-02-23 17:15:35,535 INFO    MainThread:32031 [wandb_init.py:_log_setup():371] Logging user logs to /home/zinzinbin/codes_for_study/gnn/MNIST_GNN/wandb/run-20220223_171535-2v915tow/logs/debug.log
2022-02-23 17:15:35,535 INFO    MainThread:32031 [wandb_init.py:_log_setup():372] Logging internal logs to /home/zinzinbin/codes_for_study/gnn/MNIST_GNN/wandb/run-20220223_171535-2v915tow/logs/debug-internal.log
2022-02-23 17:15:35,535 INFO    MainThread:32031 [wandb_init.py:init():404] calling init triggers
2022-02-23 17:15:35,535 INFO    MainThread:32031 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-02-23 17:15:35,536 INFO    MainThread:32031 [wandb_init.py:init():460] starting backend
2022-02-23 17:15:35,536 INFO    MainThread:32031 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-02-23 17:15:35,541 INFO    MainThread:32031 [backend.py:ensure_launched():216] starting backend process...
2022-02-23 17:15:35,544 INFO    MainThread:32031 [backend.py:ensure_launched():221] started backend process with pid: 32082
2022-02-23 17:15:35,545 INFO    MainThread:32031 [wandb_init.py:init():469] backend started and connected
2022-02-23 17:15:35,547 INFO    MainThread:32031 [wandb_init.py:init():533] updated telemetry
2022-02-23 17:15:35,555 INFO    MainThread:32031 [wandb_init.py:init():563] communicating current version
2022-02-23 17:15:36,023 INFO    MainThread:32031 [wandb_init.py:init():568] got version response upgrade_message: "wandb version 0.12.10 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-02-23 17:15:36,023 INFO    MainThread:32031 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-02-23 17:15:36,267 INFO    MainThread:32031 [wandb_init.py:init():606] starting run threads in backend
2022-02-23 17:15:37,322 INFO    MainThread:32031 [wandb_run.py:_console_start():1810] atexit reg
2022-02-23 17:15:37,322 INFO    MainThread:32031 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.REDIRECT
2022-02-23 17:15:37,323 INFO    MainThread:32031 [wandb_run.py:_redirect():1689] Redirecting console.
2022-02-23 17:15:37,324 INFO    MainThread:32031 [wandb_run.py:_redirect():1745] Redirects installed.
2022-02-23 17:15:37,324 INFO    MainThread:32031 [wandb_init.py:init():633] run started, returning control to user process
2022-02-23 17:15:43,718 INFO    MainThread:32031 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 1
2022-02-23 17:15:43,719 INFO    MainThread:32031 [wandb_run.py:_restore():1752] restore
2022-02-23 17:15:45,982 INFO    MainThread:32031 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 835
  total_bytes: 835
}

2022-02-23 17:15:46,237 INFO    MainThread:32031 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 835
  total_bytes: 835
}

2022-02-23 17:15:46,339 INFO    MainThread:32031 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 835
  total_bytes: 12735
}

2022-02-23 17:15:46,442 INFO    MainThread:32031 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 835
  total_bytes: 12735
}

2022-02-23 17:15:46,543 INFO    MainThread:32031 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 835
  total_bytes: 12735
}

2022-02-23 17:15:46,646 INFO    MainThread:32031 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10659
  total_bytes: 12735
}

2022-02-23 17:15:46,749 INFO    MainThread:32031 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12735
  total_bytes: 12735
}

2022-02-23 17:15:46,851 INFO    MainThread:32031 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12735
  total_bytes: 12735
}

2022-02-23 17:15:46,959 INFO    MainThread:32031 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12735
  total_bytes: 12735
}

2022-02-23 17:15:47,062 INFO    MainThread:32031 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12735
  total_bytes: 12735
}

2022-02-23 17:15:47,165 INFO    MainThread:32031 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12735
  total_bytes: 12735
}

2022-02-23 17:15:47,853 INFO    MainThread:32031 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12735
  total_bytes: 12735
}

2022-02-23 17:15:48,435 INFO    MainThread:32031 [wandb_run.py:_wait_for_finish():1912] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12735
  total_bytes: 12735
}
local_info {
}

2022-02-23 17:15:49,508 INFO    MainThread:32031 [wandb_run.py:_append_files():2180] logging synced files
